export type ShareCardPaletteColor = {
  hex: string;
  label?: string;
};

type ShareCardOptions = {
  title: string;
  subtitle: string;
  photoDataUrl?: string | null;
  palette: ShareCardPaletteColor[];
};

function drawRoundedRect(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number
) {
  const radius = Math.max(0, Math.min(r, Math.min(w, h) / 2));
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.arcTo(x + w, y, x + w, y + h, radius);
  ctx.arcTo(x + w, y + h, x, y + h, radius);
  ctx.arcTo(x, y + h, x, y, radius);
  ctx.arcTo(x, y, x + w, y, radius);
  ctx.closePath();
}

async function loadImage(src: string): Promise<HTMLImageElement> {
  return await new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error("Failed to load image"));
    img.src = src;
  });
}

function canvasToBlob(canvas: HTMLCanvasElement): Promise<Blob> {
  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (!blob) reject(new Error("Failed to render image"));
      else resolve(blob);
    }, "image/png");
  });
}

export async function renderShareCard(options: ShareCardOptions): Promise<Blob> {
  const width = 1080;
  const height = 1350;

  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas not supported");

  // Background gradient
  const bg = ctx.createLinearGradient(0, 0, width, height);
  bg.addColorStop(0, "#F96ED6");
  bg.addColorStop(1, "#EFF66F");
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, width, height);

  // Inner panel
  const pad = 56;
  const panelX = pad;
  const panelY = 80;
  const panelW = width - pad * 2;
  const panelH = height - 160;

  ctx.fillStyle = "rgba(255,255,255,0.96)";
  ctx.strokeStyle = "rgba(20,22,36,0.10)";
  ctx.lineWidth = 2;
  drawRoundedRect(ctx, panelX, panelY, panelW, panelH, 48);
  ctx.fill();
  ctx.stroke();

  // Title
  ctx.fillStyle = "rgba(20,22,36,0.92)";
  ctx.font = "900 54px Montserrat, system-ui, -apple-system, sans-serif";
  ctx.fillText("ColorSnap", panelX + 56, panelY + 92);

  // Subtitle
  ctx.font = "800 44px Montserrat, system-ui, -apple-system, sans-serif";
  ctx.fillText(options.title, panelX + 56, panelY + 156);
  ctx.font = "700 28px Montserrat, system-ui, -apple-system, sans-serif";
  ctx.fillStyle = "rgba(20,22,36,0.70)";
  ctx.fillText(options.subtitle, panelX + 56, panelY + 206);

  // Photo
  const photoX = panelX + 56;
  const photoY = panelY + 250;
  const photoW = 420;
  const photoH = 420;

  ctx.save();
  drawRoundedRect(ctx, photoX, photoY, photoW, photoH, 44);
  ctx.clip();

  if (options.photoDataUrl) {
    try {
      const img = await loadImage(options.photoDataUrl);
      const scale = Math.max(photoW / img.width, photoH / img.height);
      const dw = img.width * scale;
      const dh = img.height * scale;
      const dx = photoX + (photoW - dw) / 2;
      const dy = photoY + (photoH - dh) / 2;
      ctx.drawImage(img, dx, dy, dw, dh);
    } catch {
      ctx.fillStyle = "rgba(20,22,36,0.06)";
      ctx.fillRect(photoX, photoY, photoW, photoH);
    }
  } else {
    ctx.fillStyle = "rgba(20,22,36,0.06)";
    ctx.fillRect(photoX, photoY, photoW, photoH);
  }
  ctx.restore();

  // Photo border
  ctx.strokeStyle = "rgba(20,22,36,0.12)";
  ctx.lineWidth = 2;
  drawRoundedRect(ctx, photoX, photoY, photoW, photoH, 44);
  ctx.stroke();

  // Palette grid
  const gridX = panelX + 56 + photoW + 56;
  const gridY = photoY;
  const swatch = 132;
  const gap = 18;
  const cols = 3;

  const palette = options.palette.slice(0, 12);
  palette.forEach((c, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = gridX + col * (swatch + gap);
    const y = gridY + row * (swatch + gap);

    ctx.fillStyle = c.hex;
    ctx.strokeStyle = "rgba(20,22,36,0.10)";
    ctx.lineWidth = 2;
    drawRoundedRect(ctx, x, y, swatch, swatch, 28);
    ctx.fill();
    ctx.stroke();
  });

  // Footer
  ctx.fillStyle = "rgba(20,22,36,0.55)";
  ctx.font = "700 22px Montserrat, system-ui, -apple-system, sans-serif";
  ctx.fillText(
    "Generated by ColorSnap (demo) • colors may vary by lighting",
    panelX + 56,
    panelY + panelH - 56
  );

  return await canvasToBlob(canvas);
}
